//! Core Types
export const GET_MESSAGES = "GET_MESSAGES";
export const GET_ERRORS = "GET_ERRORS";

//! Auth types
export const USER_LOADED = "ADMIN_LOADED";
export const USER_LOADING = "ADMIN_LOADING";
export const GET_USER = "GET_USER";
export const REFRESH_AUTH = "REFRESH_AUTH";
export const AUTH_ERRORS = "AUTH_ERRORS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOG_OUT = "LOG_OUT";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const USER_ERRORS = "USER_ERRORS";

export const RETAILER_PRODUCTS_LOADED = "RETAILER_PRODUCTS_LOADED";
export const RETAILER_PRODUCTS_SEARCHED = "RETAILER_PRODUCTS_SEARCHED";
export const RETAILER_PRODUCTS_LOADING = "RETAILER_PRODUCTS_LOADING";
export const RETAILER_PRODUCTS_ERROR = "RETAILER_PRODUCTS_ERROR";
export const RETAILER_CATEGORIES_LOADED = "RETAILER_CATEGORIES_LOADED";
export const RETAILER_SUB_CATEGORIES_LOADED = "RETAILER_SUB_CATEGORIES_LOADED";
export const RETAILER_NEW_ARRIVALS = "RETAILER_NEW_ARRIVALS";
export const RETAILER_CATEGORY_PRODUCTS = "RETAILER_CATEGORY_PRODUCTS";
export const RETAILER_PRODUCT_DETAIL = "RETAILER_PRODUCT_DETAIL";
export const RETAILER_FAV_PRODUCT = "RETAILER_FAV_PRODUCT";
export const RETAILER_ADD_FAV_PRODUCT = "RETAILER_ADD_FAV_PRODUCT";
export const RETAILER_DELETE_FAV_PRODUCT = "RETAILER_DELETE_FAV_PRODUCT";
export const RETAILER_CLEAR_FAV_PRODUCT = "RETAILER_CLEAR_FAV_PRODUCT";
export const RETAILER_PRODUCTS_SLABS = "RETAILER_PRODUCTS_SLABS";

export const RETAILER_BANNERS_LOADED = "RETAILER_BANNERS_LOADED";
export const RETAILER_BANNERS_LOADING = "RETAILER_BANNERS_LOADING";
export const RETAILER_BANNERS_ERROR = "RETAILER_BANNERS_ERROR";

export const RETAILER_OFFERS_ERROR = "RETAILER_OFFERS_ERROR";
export const RETAILER_OFFERS_LOADED = "RETAILER_OFFERS_LOADED";
export const RETAILER_OFFERS_LOADING = "RETAILER_OFFERS_LOADING";
export const RETAILER_OFFERS_DETAILS = "RETAILER_OFFERS_DETAILS";

export const RETAILER_CART_LOADED = "RETAILER_CART_LOADED";
export const RETAILER_CART_LOADING = "RETAILER_CART_LOADING";
export const RETAILER_CART_ADDED = "RETAILER_CART_ADDED";
export const RETAILER_CART_UPDATE_TOTAL = "RETAILER_CART_UPDATE_TOTAL";
export const RETAILER_CART_DELETE = "RETAILER_CART_DELETE";
export const RETAILER_CART_ERROR = "RETAILER_CART_ERROR";
export const RETAILER_CART_CHECKOUT = "RETAILER_CART_CHECKOUT";
export const RETAILER_CART_CLEAR = "RETAILER_CART_CLEAR";
export const RETAILER_VIEW_ORDERS = "RETAILER_VIEW_ORDERS";
export const RETAILER_ORDER_CONFIRMATION = "RETAILER_ORDER_CONFIRMATION";
export const RETAILER_ORDER_REFRESH = "RETAILER_ORDER_REFRESH";
export const RETAILER_ORDER_CANCELLATION = "RETAILER_ORDER_CANCELLATION";
export const RETAILER_VIEW_DIST_ORDERS = "RETAILER_VIEW_DIST_ORDERS";

export const RETAILER_DIST_ERROR = "RETAILER_DIST_ERROR";
export const RETAILER_DIST_LOADED = "RETAILER_DIST_LOADED";
export const RETAILER_DIST_LOADING = "RETAILER_DIST_LOADING";
export const RETAILER_DIST_DETAILS = "RETAILER_DIST_DETAILS";
